name: build

on:
  push:
    branches:
      - "docker"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . -t dingocoin/dingocoin:${GITHUB_SHA} --platform linux/amd64
          docker push dingocoin/dingocoin:${GITHUB_SHA}
